name: bvt-msvc14

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false

jobs:
  bvt-msvc14:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: build with cmake
      run: |
        cmake . -B build
        cmake --build ./build -j8 --config Release

    - name: run tests
      run: |
        cd ./build
        ctest -j8 -C Release
