name: Test-CI

on:
  push:
    branches:
      - 'main'
      - 'next'
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '**.md'

env:
  BUILD_TYPE: Release

jobs:
  run-bvt-gcc14:
    uses: fenglielie/cmakezero/.github/workflows/bvt-gcc14.yml@main
    name: run bvt with g++ 14

  run-bvt-clang20:
    uses: fenglielie/cmakezero/.github/workflows/bvt-clang20.yml@main
    name: run bvt with clang 20

  run-bvt-msvc14:
    uses: fenglielie/cmakezero/.github/workflows/bvt-msvc14.yml@main
    name: run bvt with msvc14 (vs2022)
